#!/bin/bash

# Script must be run as:
#
# $ . cdls directory
#
# This is due to using 'cd' in A script which
# creates A new bash shell.

if [ -z "$1" ]
 then
  printf "Failed: Directory name must be entered as runtime argument.\n"
else
 cd $1
 ls
fi

